### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by johnsylvain** [johnsylvain/reddit-showerthoughts-newtab#4]
Unit tests should be added. They should cover:
- data fetching 
- getting and setting data from `chrome.storage.local`
- data caching and cache expiration times

**Comment by ypahalajani** [comment]
@johnsylvain : I'm up for this.

**Comment by ypahalajani** [comment]
@johnsylvain: I will be using Jasmine 2.5.2 for writing test suite of this extension. I read about Jasmine and it's usage. I've integrated the Jasmine test runner with the extension.
Here are my initial thoughts - Currently, the **App** prototype is not modular i.e. I need to write test suite for App module but in background.js, the script calls the init function, the moment it is read by browser. So, i am planning to make a global app module in a separate file and then calling the init function in background.js. In this way, i can mock the app object to test various function that are defined in it like - loadState, getThoughts, etc. This is all that I have thought of, for now. Let me know, what do you think about this?

**Comment by johnsylvain** [comment]
Makes sense to me. I would like there to be no modifications to `background.js` when you submit a PR and have all testing files in a `test` directory.

**Comment by ypahalajani** [comment]
All the test files will be in the **tests** directory, indeed. Regarding the modifications part, I assure you that _the logic won't change in any circumstances_, only the structure might need to change in the process of making it modular (it being the `App prototype`).

**Comment by ypahalajani** [comment]
@johnsylvain: Hi, I couldn't find a way to test native JS promises in Jasmine so I have moved on to mocha and chai for testing. I've integrated the setup and written a trivial test case for checking the integration and it is working fine. Also, I need to make the functions inside App => pure functions, so that they are independent and can be easily tested - keeping the logic as it is.

Update: Jasmine 2.0 has support for testing promises. I'll read and try to implement it.
